---
ID: "d1b623ba-a97f-5f4d-b974-c09d9b3edaf7"
Parent: "ab087ebc-10a6-5e5e-bad7-7039149c2812"
Template: "ab087ebc-10a6-5e5e-bad7-7039149c2812"
Path: "/sitecore/templates/Project/nextjsandazurebc/Styleguide-FieldUsage-Number/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210525T185241Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f049aec7-ad4c-40db-a10e-67fb2dbed470"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210525T185241Z
