---
ID: "7e175dce-e717-5968-b1be-abee3e39d165"
Parent: "f4f8b165-6a4e-5729-8372-cc80737749a0"
Template: "f4f8b165-6a4e-5729-8372-cc80737749a0"
Path: "/sitecore/templates/Project/nextjsandazurebc/Styleguide-FieldUsage-ItemLink/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210525T185239Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f68b6e71-9b47-492f-ae2c-ac21f5d5276e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210525T185239Z
