---
ID: "48940bd9-33c8-57e6-808f-fc20ae919d98"
Parent: "c0c9bd58-ed98-5f84-9320-dc9bed38c6e4"
Template: "c0c9bd58-ed98-5f84-9320-dc9bed38c6e4"
Path: "/sitecore/templates/Project/nextjsandazurebc/Styleguide-ContentList-Item-Template/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210525T185234Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fd683d2f-d155-41fc-9034-559a9cd349e5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210525T185234Z
