---
ID: "c8c4b0bf-dc48-5d29-8bca-034be9e859fd"
Parent: "9cd956e5-52d5-5e53-965c-ba37afe26ca2"
Template: "9cd956e5-52d5-5e53-965c-ba37afe26ca2"
Path: "/sitecore/templates/Project/nextjsandazurebc/Styleguide-Layout-Tabs/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210525T185245Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "128a7914-7801-4cc9-ab3a-6998a4d03c20"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210525T185245Z
